name: jp_learning
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.1
  http: ^1.4.0
  html: ^0.15.6
  ruby_text: ^3.0.3
  audioplayers: ^6.4.0
  uuid: ^4.5.1
  translator: ^1.0.3+1
  flutter_tts: 4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/