// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7G1TvTw3Z92V2MvlpOp2GixMi6exXG9k',
    appId: '1:816986072148:web:c4b1e97c22bbda9bf7f9c1',
    messagingSenderId: '816986072148',
    projectId: 'jp-learning-26211',
    authDomain: 'jp-learning-26211.firebaseapp.com',
    storageBucket: 'jp-learning-26211.firebasestorage.app',
    measurementId: 'G-Q110EQ7GJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEKf3edb-LBx53qFynaLJz3ByFhLhreA',
    appId: '1:816986072148:android:64697919202741b0f7f9c1',
    messagingSenderId: '816986072148',
    projectId: 'jp-learning-26211',
    storageBucket: 'jp-learning-26211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1YxHta8pjWSS_yxhGhHmnTfsuhYW0fDs',
    appId: '1:816986072148:ios:d1a3ea00b967d7e3f7f9c1',
    messagingSenderId: '816986072148',
    projectId: 'jp-learning-26211',
    storageBucket: 'jp-learning-26211.firebasestorage.app',
    iosBundleId: 'com.example.jpLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1YxHta8pjWSS_yxhGhHmnTfsuhYW0fDs',
    appId: '1:816986072148:ios:d1a3ea00b967d7e3f7f9c1',
    messagingSenderId: '816986072148',
    projectId: 'jp-learning-26211',
    storageBucket: 'jp-learning-26211.firebasestorage.app',
    iosBundleId: 'com.example.jpLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7G1TvTw3Z92V2MvlpOp2GixMi6exXG9k',
    appId: '1:816986072148:web:d5ecdb1c5c4d63c9f7f9c1',
    messagingSenderId: '816986072148',
    projectId: 'jp-learning-26211',
    authDomain: 'jp-learning-26211.firebaseapp.com',
    storageBucket: 'jp-learning-26211.firebasestorage.app',
    measurementId: 'G-643NM6GVXN',
  );

}